package gw.specContrib.classes.property_Declarations.sameErasureCases

uses java.lang.Integer
uses java.util.ArrayList

enhancement Errant_SameErasureFunctionsEnh_2: Errant_SameErasureFunctionsClass_2 {

  //functions vs functions in enhancement
  function foo1(a : ArrayList<Object>){}            //## issuekeys: THE METHOD 'FOO1(ARRAYLIST<OBJECT>)' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.SAMEERASURECASES.TOBEPUSHED.ERRANT_SAMEERASUREFUNCTIONSCLASS_2'. ENHANCEMENTS CANNOT OVERRIDE METHODS.
  function foo2(a : ArrayList){}            //## issuekeys: THE METHOD 'FOO2(ARRAYLIST)' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.SAMEERASURECASES.TOBEPUSHED.ERRANT_SAMEERASUREFUNCTIONSCLASS_2'. ENHANCEMENTS CANNOT OVERRIDE METHODS.
  function foo3(a : ArrayList<Integer>){}            //## issuekeys: THE METHOD 'FOO3(ARRAYLIST<INTEGER>)' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.SAMEERASURECASES.TOBEPUSHED.ERRANT_SAMEERASUREFUNCTIONSCLASS_2'. ENHANCEMENTS CANNOT OVERRIDE METHODS.
  function foo4(a : ArrayList<String>){}
  //IDE-1919 OS Gosu Issue. Waiting for the decision
  function foo5(a : ArrayList<Integer>){}                //## issuekeys: CONFLICT
  function foo6(a : ArrayList<java.lang.Number>){}

  //Properties vs properties in enhancement
  property set Property1(a : ArrayList<Object>) {}            //## issuekeys: THE PROPERTY OR FIELD 'PROPERTY1' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.SAMEERASURECASES.TOBEPUSHED.ERRANT_SAMEERASUREFUNCTIONSCLASS_2'. ENHANCEMENTS CANNOT OVERRIDE PROPERTIES.
  property set Property2(a : ArrayList) {}            //## issuekeys: THE PROPERTY OR FIELD 'PROPERTY2' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.SAMEERASURECASES.TOBEPUSHED.ERRANT_SAMEERASUREFUNCTIONSCLASS_2'. ENHANCEMENTS CANNOT OVERRIDE PROPERTIES.
  property set Property3(a : ArrayList<Integer>) {}            //## issuekeys: THE PROPERTY OR FIELD 'PROPERTY3' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.SAMEERASURECASES.TOBEPUSHED.ERRANT_SAMEERASUREFUNCTIONSCLASS_2'. ENHANCEMENTS CANNOT OVERRIDE PROPERTIES.
  property set Property4(a : ArrayList<String>) {}            //## issuekeys: THE PROPERTY OR FIELD 'PROPERTY4' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.SAMEERASURECASES.TOBEPUSHED.ERRANT_SAMEERASUREFUNCTIONSCLASS_2'. ENHANCEMENTS CANNOT OVERRIDE PROPERTIES.
  property set Property5(a : ArrayList<Integer>) {}            //## issuekeys: THE PROPERTY OR FIELD 'PROPERTY5' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.SAMEERASURECASES.TOBEPUSHED.ERRANT_SAMEERASUREFUNCTIONSCLASS_2'. ENHANCEMENTS CANNOT OVERRIDE PROPERTIES.
  property set Property6(a : ArrayList<java.lang.Number>) {}            //## issuekeys: THE PROPERTY OR FIELD 'PROPERTY6' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.SAMEERASURECASES.TOBEPUSHED.ERRANT_SAMEERASUREFUNCTIONSCLASS_2'. ENHANCEMENTS CANNOT OVERRIDE PROPERTIES.

  //Properties vs functions in enhancement
  function setProperty21(a : ArrayList<Object>) {}            //## issuekeys: THE METHOD 'SETPROPERTY21(ARRAYLIST<OBJECT>)' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.SAMEERASURECASES.TOBEPUSHED.ERRANT_SAMEERASUREFUNCTIONSCLASS_2'. ENHANCEMENTS CANNOT OVERRIDE METHODS.
  function setProperty22(a : ArrayList) {}            //## issuekeys: THE METHOD 'SETPROPERTY22(ARRAYLIST)' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.SAMEERASURECASES.TOBEPUSHED.ERRANT_SAMEERASUREFUNCTIONSCLASS_2'. ENHANCEMENTS CANNOT OVERRIDE METHODS.
  function setProperty23(a : ArrayList<Integer>) {}            //## issuekeys: THE METHOD 'SETPROPERTY23(ARRAYLIST<INTEGER>)' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.SAMEERASURECASES.TOBEPUSHED.ERRANT_SAMEERASUREFUNCTIONSCLASS_2'. ENHANCEMENTS CANNOT OVERRIDE METHODS.
  //IDE-1918 - OS Gosu shows error here. Waiting for decision
  function setProperty24(a : ArrayList<String>) {}          //## issuekeys: CONFLICT
  function setProperty25(a : ArrayList<Integer>) {}         //## issuekeys: CONFLICT
  function setProperty26(a : ArrayList<java.lang.Number>) {}    //## issuekeys: CONFLICT

  //Functions vs properties in enhancement
  property set Foo21(a: ArrayList<Object>){}            //## issuekeys: THE METHOD 'SETFOO21(ARRAYLIST<OBJECT>)' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.SAMEERASURECASES.TOBEPUSHED.ERRANT_SAMEERASUREFUNCTIONSCLASS_2'. ENHANCEMENTS CANNOT OVERRIDE METHODS.
  property set Foo22(a: ArrayList){}            //## issuekeys: THE METHOD 'SETFOO22(ARRAYLIST)' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.SAMEERASURECASES.TOBEPUSHED.ERRANT_SAMEERASUREFUNCTIONSCLASS_2'. ENHANCEMENTS CANNOT OVERRIDE METHODS.
  property set Foo23(a: ArrayList<Integer>){}            //## issuekeys: THE METHOD 'SETFOO23(ARRAYLIST<INTEGER>)' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.SAMEERASURECASES.TOBEPUSHED.ERRANT_SAMEERASUREFUNCTIONSCLASS_2'. ENHANCEMENTS CANNOT OVERRIDE METHODS.
  //IDE-1918 - OS Gosu shows error here. Waiting for the decision
  property set Foo24(a: ArrayList<String>){}               //## issuekeys: CONFLICT
  property set Foo25(a: ArrayList<Integer>){}               //## issuekeys: CONFLICT
  property set Foo26(a: ArrayList<java.lang.Number>){}     //## issuekeys: CONFLICT


  //As properties vs As properties in subclass
 //Enhancements cannot have fields.

  //As propertiPes vs properties in subclass
  property set Property41(a: ArrayList<Object>){}            //## issuekeys: THE PROPERTY OR FIELD 'PROPERTY41' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.SAMEERASURECASES.TOBEPUSHED.ERRANT_SAMEERASUREFUNCTIONSCLASS_2'. ENHANCEMENTS CANNOT OVERRIDE PROPERTIES.
  property set Property42(a: ArrayList){}            //## issuekeys: THE PROPERTY OR FIELD 'PROPERTY42' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.SAMEERASURECASES.TOBEPUSHED.ERRANT_SAMEERASUREFUNCTIONSCLASS_2'. ENHANCEMENTS CANNOT OVERRIDE PROPERTIES.
  property set Property43(a: ArrayList<Integer>){}            //## issuekeys: THE PROPERTY OR FIELD 'PROPERTY43' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.SAMEERASURECASES.TOBEPUSHED.ERRANT_SAMEERASUREFUNCTIONSCLASS_2'. ENHANCEMENTS CANNOT OVERRIDE PROPERTIES.
  property set Property44(a: ArrayList<String>){}            //## issuekeys: THE PROPERTY OR FIELD 'PROPERTY44' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.SAMEERASURECASES.TOBEPUSHED.ERRANT_SAMEERASUREFUNCTIONSCLASS_2'. ENHANCEMENTS CANNOT OVERRIDE PROPERTIES.
  property set Property45(a: ArrayList<Integer>){}            //## issuekeys: THE PROPERTY OR FIELD 'PROPERTY45' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.SAMEERASURECASES.TOBEPUSHED.ERRANT_SAMEERASUREFUNCTIONSCLASS_2'. ENHANCEMENTS CANNOT OVERRIDE PROPERTIES.
  property set Property46(a: ArrayList<java.lang.Number>){}            //## issuekeys: THE PROPERTY OR FIELD 'PROPERTY46' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.SAMEERASURECASES.TOBEPUSHED.ERRANT_SAMEERASUREFUNCTIONSCLASS_2'. ENHANCEMENTS CANNOT OVERRIDE PROPERTIES.

  //As properties vs functions in subclass
  function setProperty51(a : ArrayList<Object>) {}            //## issuekeys: THE METHOD 'SETPROPERTY51(ARRAYLIST<OBJECT>)' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.SAMEERASURECASES.TOBEPUSHED.ERRANT_SAMEERASUREFUNCTIONSCLASS_2'. ENHANCEMENTS CANNOT OVERRIDE METHODS.
  function setProperty52(a : ArrayList) {}            //## issuekeys: THE METHOD 'SETPROPERTY52(ARRAYLIST)' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.SAMEERASURECASES.TOBEPUSHED.ERRANT_SAMEERASUREFUNCTIONSCLASS_2'. ENHANCEMENTS CANNOT OVERRIDE METHODS.
  function setProperty53(a : ArrayList<Integer>) {}            //## issuekeys: THE METHOD 'SETPROPERTY53(ARRAYLIST<INTEGER>)' IS ALREADY DEFINED IN THE TYPE 'GW.SPECCONTRIB.AAA.PARSERVSOPENSOURCE.SAMEERASURECASES.TOBEPUSHED.ERRANT_SAMEERASUREFUNCTIONSCLASS_2'. ENHANCEMENTS CANNOT OVERRIDE METHODS.
  //IDE-1918 WAITING
  function setProperty54(a : ArrayList<String>) {}             //## issuekeys: CONFLICT
  function setProperty55(a : ArrayList<Integer>) {}            //## issuekeys: CONFLICT
  function setProperty56(a : ArrayList<java.lang.Number>) {}    //## issuekeys: CONFLICT

  //properties vs As properties in subclass
  //Enhancements cannot have fields.

  //functions vs As properties in subclass
  //Enhancements cannot have fields.

}
